server:
  port: 8081

spring:
  profiles:
    active: postgres


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.commerce.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: debug
    org.hibernate.SQL: debug
    # 바인딩 파라미터 출력
    org.hibernate.orm.jdbc.bind: trace


file:
  upload-dir: D:/dev/product-images/

